/**
 * İngilizce sözlük. Anahtar = Türkçe metnin kendisi.
 * Karşılığı olmayan metin Türkçe görünür (arayüz bozulmaz).
 */
const EN: Record<string, string> = {
  /* --- başlık ve genel --- */
  "🗄️ Proxmox → Google Drive Yedek": "🗄️ Proxmox → Google Drive Backup",
  "⚙ Ayarlar": "⚙ Settings", "+ Yeni Plan": "+ New Plan", "Vazgeç": "Cancel",
  "Kaydet": "Save", "Kapat": "Close", "Sil": "Delete", "Ekle": "Add", "Test": "Test",
  "Düzenle": "Edit", "‹ Geri": "‹ Back", "İleri ›": "Next ›", "— seç —": "— select —",
  "Seçim": "Choice", "Özet": "Summary", "Log": "Log", "Tümü": "All", "Sistem": "System",
  "plan": "plan", "çalışıyor": "running", "durum: ": "status: ",
  "mail profili yok": "no mail profile", "Hesap": "Account", "Klasör": "Folder",
  "Sunucu": "Server", "Port": "Port", "Kullanıcı": "Username", "Şifre": "Password",
  "Gönderen": "From", "Güvenlik": "Security", "Alıcı": "Recipient", "Saat": "Time",
  "Günler": "Days", "Gün": "Day", "gün": "days", "saat": "hours", "sn": "s", "dk": "min",
  "set": "sets", "adet": "count", "her gün": "every day", "hiçbiri": "none",
  "kapalı": "disabled", "etkin": "enabled", "atlandı": "skipped", "başarılı": "successful",
  "hata": "error", "yok": "none", "boş": "free", "çöp": "trash", "Çöp": "Trash",
  "hazır": "ready", "Kurulum": "Setup", "Örnek:": "Example:", "Anahtar": "Key",
  "Varsayılan": "Default", "Açıklama": "Description", "min": "min",

  /* --- plan kartı --- */
  "● ÇALIŞIYOR": "● RUNNING", "KAPALI": "DISABLED", "✔ BAŞARILI": "✔ SUCCESS",
  "✖ HATA": "✖ FAILED", "⏸ ATLANDI": "⏸ SKIPPED",
  "Kaynak": "Source", "Hedef": "Target", "Program": "Schedule", "Sonraki": "Next",
  "Saklama": "Retention", "Son çalışma": "Last run", "Haftalık rapor": "Weekly report",
  "▶ Yedekle": "▶ Back up", "🧹 Retention": "🧹 Retention", "🗑 Çöpü Boşalt": "🗑 Empty Trash",
  "📊 Rapor": "📊 Report", "✉ Test": "✉ Test", "✎ Düzenle": "✎ Edit",
  " dosya)": " files)", " gün": " days", " set": " sets", " · min ": " · min ",
  " set · çöp ": " sets · trash ",

  /* --- ilerleme --- */
  "Başlangıç": "Started", "Geçen": "Elapsed", "Aktarılan": "Transferred", "Hız": "Speed",
  "Kalan süre": "Time left", "Tahmini bitiş": "Est. finish", "Çalışıyor": "Running",
  "Hazırlanıyor": "Preparing", "Drive'a yükleniyor": "Uploading to Drive",
  "Drive listeleniyor": "Listing Drive", "Proxmox yedeği bekleniyor": "Waiting for Proxmox backup",
  "Eski yedekler çöpe taşınıyor": "Moving old backups to trash",
  "Çöp kutusu temizleniyor": "Emptying trash", "Durum güncelleniyor": "Updating status",
  "Bu iş sunucuda çalışıyor — sayfayı yenilesen de kapatsan da devam eder.":
    "This job runs on the server — it continues even if you refresh or close the page.",

  /* --- detay kartları --- */
  "Yedek dosyası": "Backup files", "Toplam boyut": "Total size",
  "Son yedek yaşı": "Newest backup age", "Çöpte bekleyen": "Waiting in trash",
  "Çöp süresi": "Trash period", "Google Drive kullanımı": "Google Drive usage",
  "Yedekler (Drive)": "Backups (Drive)", "Tarih": "Date", "VM/CT": "VM/CT",
  "Boyut": "Size", "Dosya": "File", "Kalan": "Left", "yedek yok": "no backups",
  "Çalışma geçmişi": "Run history", "Zaman": "Time", "Durum": "Status", "Tetik": "Trigger",
  "kayıt yok": "no records", "süre dolunca kalıcı silinir": "permanently deleted when time is up",
  "Google çöp kutusu (": "Google trash (",

  /* --- sihirbaz --- */
  "🧭 Yeni plan sihirbazı": "🧭 New plan wizard",
  "Adım adım ilerle. Hiçbir şey kaydedilmez, son adımda onaylarsın.":
    "Go step by step. Nothing is saved until you confirm on the last step.",
  "Tüm ayarlar tek sayfada. Alan adlarının üstüne gelince açıklama çıkar.":
    "All settings on one page. Hover a field label for an explanation.",
  "1. Plan": "1. Plan", "2. Kaynak": "2. Source", "3. Hedef": "3. Target",
  "4. Saklama": "4. Retention", "5. Zamanlama": "5. Schedule", "6. Aktarım": "6. Transfer",
  "7. Bildirim": "7. Notify", "8. Özet": "8. Summary",
  "Bu plana bir ad ver": "Give this plan a name",
  "Proxmox'ta hangi klasör yedeklenecek": "Which folder on Proxmox to back up",
  "Hangi Google hesabına, hangi klasöre": "Which Google account and folder",
  "Yedekler ne kadar süre kalsın": "How long backups are kept",
  "Ne zaman çalışsın, çakışma nasıl önlensin": "When to run and how to avoid conflicts",
  "Hız ve kaynak kullanımı": "Speed and resource usage",
  "Kim, ne zaman haberdar olsun": "Who gets notified and when",
  "Kaydetmeden önce kontrol et": "Check before saving",

  /* --- hazır senaryolar --- */
  "Hazır senaryolar": "Presets", "📅 Günlük — 14 gün": "📅 Daily — 14 days",
  "🗄️ Haftalık arşiv — 6 ay": "🗄️ Weekly archive — 6 months",
  "🔒 Kritik — 30 gün": "🔒 Critical — 30 days", "🧪 Test": "🧪 Test",
  "senaryo yüklendi — kaydetmeden uygulanmaz": "preset loaded — not applied until you save",

  /* --- form alanları --- */
  "Genel": "General", "Plan adı": "Plan name", "Etkin": "Enabled",
  "zamanlayıcı bu planı çalıştırsın": "let the scheduler run this plan",
  "Kaynak (Proxmox)": "Source (Proxmox)", "Yedek klasörü": "Backup folder",
  "Hedef (Google hesabı)": "Target (Google account)",
  "Saklama süreleri": "Retention periods", "Drive'da tut (gün)": "Keep on Drive (days)",
  "En az set (adet)": "Minimum sets (count)", "Çöpte bekle (gün)": "Wait in trash (days)",
  "Zamanlama": "Schedule", "Aktarım": "Transfer", "Bildirim": "Notifications",
  "Hız sınırı": "Speed limit", "Saatlik çizelge": "Hourly schedule",
  "Sadece yükleme": "Upload only", "Eşzamanlı transfer": "Concurrent transfers",
  "Checkers": "Checkers", "Drive parça boyutu": "Drive chunk size",
  "Ek rclone argümanı": "Extra rclone arguments", "Gönderen profili": "Sender profile",
  "Ne zaman mail": "When to email", "✔ Başarılı olunca": "✔ On success",
  "✖ Hata olunca": "✖ On failure", "⏸ Atlanınca": "⏸ On skip",
  "Rapor gönder": "Send report", "Dönem (gün)": "Period (days)",
  "Uyarı eşiği (gün)": "Warning threshold (days)", "Kota uyarısı (%)": "Quota warning (%)",
  "Rapor alıcısı": "Report recipient",
  "haftalık özet raporu gönder": "send a weekly summary report",

  /* --- çakışma koruması --- */
  "Proxmox ile çakışma koruması": "Proxmox conflict protection",
  "vzdump'ı bekle": "Wait for vzdump", "En fazla bekleme (dk)": "Max wait (min)",
  "Dosya yaşı (dk)": "File age (min)", "Atlanacak desenler": "Skip patterns",
  "Hatada retention": "Retention on failure",
  "Proxmox yedeği biterken bekle": "wait for the Proxmox backup to finish",
  "yükleme başarısız olsa da eskileri sil": "delete old ones even if the upload failed",

  /* --- otomatik bant genişliği --- */
  "Otomatik bant genişliği": "Automatic bandwidth", "Otomatik mod": "Automatic mode",
  "Hat kapasitesi": "Link capacity", "Diğerlerine ayrılan": "Reserved for others",
  "Alt sınır": "Lower bound", "Üst sınır": "Upper bound", "Ağ arayüzü": "Network interface",
  "Ölçüm aralığı (sn)": "Measure interval (s)", "Yumuşatma (0-1)": "Smoothing (0-1)",
  "Değişim eşiği (%)": "Change threshold (%)",
  "hattaki diğer trafiğe göre kendini ayarla": "adapt to other traffic on the link",
  "sınır yalnızca yüklemeye uygulansın": "apply the limit to uploads only",
  "Çizelgesiz": "No schedule", "Mesai dostu": "Office friendly", "Sadece gece": "Night only",

  /* --- hesaplar --- */
  "👤 Google hesapları": "👤 Google accounts", "👤 Yönet": "👤 Manage",
  "＋ Yeni hesap": "＋ New account", "Yeni Google hesabı yetkilendir": "Authorise a new Google account",
  "Hesap adı": "Account name", "Tarayıcıyla yetkilendir": "Authorise with browser",
  "Hazır jetonu yapıştır": "Paste an existing token", "Tünel komutu": "Tunnel command",
  "▶ Başlat": "▶ Start", "Jeton (JSON)": "Token (JSON)", "Henüz hesap yok.": "No accounts yet.",
  "jeton bekleniyor…": "waiting for token…", "iptal edildi": "cancelled",
  "kota okunamadı": "quota unreadable", "Yönetmek için tıkla": "Click to manage",

  /* --- mail profilleri --- */
  "✉ Mail gönderici profilleri": "✉ Mail sender profiles", "✉ Yönet": "✉ Manage",
  "Sağlayıcı şablonu": "Provider preset", "Profil adı": "Profile name",
  "Yeni profil": "New profile", "Test maili": "Test email",
  "Formu temizle": "Clear form", "Henüz profil yok.": "No profiles yet.",
  "Özel (elle gir)": "Custom (enter manually)",

  /* --- ayarlar --- */
  "Tüm planlar için ortak.": "Shared by all plans.", "Web arayüzü": "Web interface",
  "Dinlenen adres": "Listen address", "Yeni şifre": "New password",
  "Tazeleme (sn)": "Refresh (s)", "Gelişmiş": "Advanced", "Gezinme kökleri": "Browse roots",
  "Dosya adı kalıbı": "Filename pattern", "Geçmiş kaydı": "History entries",
  "Log satırı": "Log lines", "rclone tampon satırı": "rclone buffer lines",
  "Durum satır sınırı": "Status row limit", "Log boyutu (MB)": "Log size (MB)",
  "Saklanan log": "Logs kept", "rclone zaman aşımı (dk)": "rclone timeout (min)",
  "Hesap geneli cleanup": "Account-wide cleanup", "HTTPS": "HTTPS",
  "Sertifika": "Certificate", "Güvenli çerez": "Secure cookie",
  "Erişim kısıtlaması": "Access restriction", "İzinli ağlar": "Allowed networks",
  "Güncelleme": "Update", "Kontrol et": "Check", "Otomatik kur": "Auto install",
  "↻ Şimdi kontrol et": "↻ Check now", "⬇ Güncellemeyi kur": "⬇ Install update",
  "↶ Önceki sürüme dön": "↶ Roll back", "boş = değişmesin": "empty = unchanged",
  "günlük güncelleme kontrolü": "daily update check",
  "bulunca kendiliğinden kur": "install automatically when found",
  "çerezi sadece HTTPS'te gönder": "send the cookie over HTTPS only",
  "son çare olarak rclone cleanup çalıştır": "run rclone cleanup as a last resort",

  /* --- klasör gezgini --- */
  "📁 Yedek klasörünü seç": "📁 Choose the backup folder", "📁 Gözat": "📁 Browse",
  "Bu klasörü seç": "Use this folder", "⬆ üst klasör": "⬆ parent folder",
  "alt klasör yok": "no subfolders",

  /* --- kapasite --- */
  "📐 Önerilen süreyi uygula": "📐 Apply suggested period",
  "↻ Yeniden ölç": "↻ Measure again",
  "Kaynak ve hesap seçilince kapasite hesabı burada çıkar.":
    "The capacity estimate appears here once a source and account are chosen.",
  "ölçülüyor…": "measuring…", "ölçüm başarısız": "measurement failed",

  /* --- mesajlar --- */
  "çalışıyor…": "working…", "tamam": "done",
  "gönderiliyor…": "sending…", "kontrol ediliyor…": "checking…",
  "indiriliyor ve doğrulanıyor…": "downloading and verifying…",
  "form hatalı — kırmızı alanlara bak": "form has errors — check the red fields",
  "form hatalı": "form has errors",
  "bu adımda eksik veya hatalı alan var": "this step has missing or invalid fields",
  "önce hesap adı yaz": "enter an account name first",
  "adresi tarayıcında aç": "open the address in your browser",
  "oturum bitti": "session expired", "sunucu hatası": "server error",
  "yeni profil için şifre gerekli": "a password is required for a new profile",

  /* --- doğrulama --- */
  "plan adı gerekli": "plan name is required",
  "kaynak klasör gerekli": "source folder is required",
  "hedef klasör gerekli": "target folder is required",
  "önce bir Google hesabı ekle": "add a Google account first",
  "alıcı adresi gerekli": "recipient address is required",
  "kullanıcı adı gerekli": "username is required",
  "kalıp boş olamaz": "the pattern cannot be empty",
  "profil adı gerekli": "profile name is required",
  "geçerli bir sunucu adı yaz": "enter a valid server name",
  "geçerli JSON değil": "not valid JSON",
  "sadece harf, rakam, - ve _": "letters, digits, - and _ only",
  "ikisi birden 0 olamaz — hiç yedek kalmaz":
    "both cannot be 0 — you would keep no backups",
  "alt sınır üst sınırdan büyük olamaz":
    "the lower bound cannot exceed the upper bound",
  "geçersiz sayı": "invalid number", "bu alan gerekli": "this field is required",
  "geçersiz adres: ": "invalid address: ", "geçersiz ağ: ": "invalid network: ",

  /* --- onay soruları --- */
  "Plan silinsin mi? Drive'daki yedek dosyalarına dokunulmaz.":
    "Delete this plan? The backup files on Drive are not touched.",
  "Profil silinsin mi?": "Delete this profile?",
  "Kaydedilmemiş değişiklikler var, kapatılsın mı?":
    "There are unsaved changes. Close anyway?",
  /* --- ikinci parti --- */
  "Çar": "Wed", "Plan: ": "Plan: ", "hata: ": "error: ", "uygun.": "is a good fit.",
  "· Depo": "· Storage", " · çöp ": " · trash ", ". Örnek:": ". Example:",
  "çalışmaz": "does not run", "  ·  boş ": "  ·  free ", "  ·  çöp ": "  ·  trash ",
  " boş var.": " free.", " · güncel": " · up to date", "Düzenle: ": "Edit: ",
  "Her giriş": "Each entry", "güncel: v": "up to date: v", "çizelge: ": "schedule: ",
  " · bitiş: ": " · expires: ", "= sınırsız": "= unlimited",
  "giriş yap:": "sign in:", "· 1 Gbit ≈": "· 1 Gbit ≈", "ölçülemedi": "not measured",
  "seti korur.": "sets.", "yükleniyor…": "loading…", "(VPN ağın) ·": "(your VPN) ·",
  "Kurulu sürüm": "Installed version", "her yerden ·": "from anywhere ·",
  "ve uyarılar.": "and warnings.", "Birden fazla:": "Multiple:",
  "Kapalı bırak.": "Leave it off.", "başlatılamadı": "could not start",
  "Önerilen: <b>": "Suggested: <b>", " gün uygulandı": " days applied",
  " günlük dönem)": " day period)", " hesap tanımlı": " accounts configured",
  "API hızını kıs": "throttle API rate", "Günlük VM + CT": "Daily VM + CT",
  "Günlük yedekte": "For a daily backup", "Haftalık arşiv": "Weekly archive",
  "Yok (şifresiz)": "None (unencrypted)", "geçersiz değer": "invalid value",
  "iyi bir değer.": "is a good value.", "vzdump koruması": "vzdump protection",
  "Bağlantı şifreli": "Connection encrypted", "Günlük VM yedeği": "Daily VM backup",
  "bekle, en fazla ": "wait, at most ", "beklemeden çalış": "run without waiting",
  "yavaş hat için ·": "for a slow link ·", "ör. 30M veya boş": "e.g. 30M or empty",
  "yeni sürüm var: v": "new version available: v",
  "✉ Mail profilleri": "✉ Mail profiles", "Kurulu sürüm: <b>v": "Installed version: <b>v",
  "Proxmox depoları: ": "Proxmox storages: ", "o saatten itibaren": "from that hour on",
  "uzantısı kullanır.": "extension.", "Ölçüldü: günde <b>": "Measured: <b>",
  "çalışmaz (güvenli)": "does not run (safe)", "(boş = sabit sınır)": "(empty = fixed limit)",
  "Bit değil bayt yaz.": "Enter bytes, not bits.",
  "Drive'daki tüm çöpü": "all trash in the Drive", "SMTP sunucu adresi.": "SMTP server address.",
  "Sadece harf, rakam,": "Only letters, digits,", "yol argümanı almaz,": "takes no path argument,",
  "⚠ klasör bulunamadı": "⚠ folder not found", " gün sonra ulaşılır.": " days.",
  " günlük set, toplam ": " daily sets, total ", "SS:DD biçiminde saat": "time as HH:MM",
  "ör. 30M, 2M veya off": "e.g. 30M, 2M or off",
  "Virgülle ayır. Örnek:": "Comma separated. Example:",
  " gün</b> (boş alanın %": " days</b> (uses %",
  " gün</b> saklama + <b>": " days</b> retention + <b>",
  "RAM ≈ parça × transfer": "RAM ≈ chunk × transfers",
  "hedef Google hesabıyla": "with the target Google account",
  "senin bilgisayarındaki": "on your own computer",
  "uygun. Haftalık planda": "is right. For a weekly plan use",
  "yetkilendirme sonlandı": "authorisation ended",
  "Ölçüm ve ayar sıklığı.": "How often to measure and adjust.",
  "Outlook / Microsoft 365": "Outlook / Microsoft 365",
  "(boş = yukarıdaki alıcı)": "(empty = recipient above)",
  ", uygulama şifresi üret.": ", create an app password.",
  " gün sonra kalıcı silinir": " days it is permanently deleted",
  "Mail gönderici profilleri": "Mail sender profiles",
  "Yükleme hızın. 100 Mbit ≈": "Your upload speed. 100 Mbit ≈",
  "düz HTTP ile ayakta kalır": "stays up over plain HTTP",
  "log dosyalarını yükleme ·": "skip log files ·",
  "yap, yoksa boşuna uyarır.": "instead, or it warns needlessly.",
  "= hiç bekleme, hemen atla.": "= do not wait, skip immediately.",
  "Raporun gönderileceği gün.": "Day the report is sent.",
  "Sadece veritabanı sunucusu": "Database server only",
  "kapalı (zamanlayıcı atlar)": "disabled (scheduler skips it)",
  "yalnızca program dosyasını": "only the program file",
  " gün</b> çöp → Drive'da <b>": " days</b> trash → <b>",
  "Bu adresi tarayıcında aç ve": "Open this address in your browser and",
  "Raporun gönderileceği saat.": "Time the report is sent.",
  "Sertifikanın özel anahtarı.": "The certificate's private key.",
  " gün · VM/CT başına en az ": " days · at least ",
  "Proxmox'un kendi sertifikası:": "Proxmox's own certificate:",
  "Sertifika yüklenemezse servis": "If the certificate cannot be loaded the service",
  "(düzenlemede boş = değişmesin)": "(empty when editing = unchanged)",
  "Boşlukla ayır. vzdump yazarken": "Space separated. While writing, vzdump uses the",
  "Tahmini rclone RAM kullanımı: ": "Estimated rclone RAM use: ",
  "önce geçerli bir hesap adı yaz": "enter a valid account name first",
  "Google onaydan sonra tarayıcıyı": "After approval Google redirects the browser to",
  " set var); hedef doluluğa ancak ": " sets in the source); the target level is reached in ",
  "Her plan farklı klasöre yazmalı.": "Each plan must write to a different folder.",
  "Proxmox işin 21:00'de başlıyorsa": "If your Proxmox job starts at 21:00 then",
  "SS:DD biçiminde saat (ör. 03:00)": "time as HH:MM (e.g. 03:00)",
  "Yeni sürümün indirileceği adres.": "Where the new version is downloaded from.",
  "VM/CT bazında son yedek tarihi": "last backup date per guest",
  "⚠ Bu süre hesaba <b>sığmaz</b>: ": "⚠ This period does <b>not fit</b>: ",
  "Mesaide hattı boğma, gece hızlan:": "Go easy during work hours, fast at night:",
  "Plan hedefinde görünecek kısa ad.": "Short name shown in the plan target.",
  "Rapor kaç günlük dönemi kapsasın.": "How many days the report covers.",
  "= çöpe uğramadan hemen kalıcı sil.": "= delete permanently without using the trash.",
  "jeton alındı, hesap oluşturuluyor…": "token received, creating account…",
  'klasör adında : * ? " < > | olamaz': 'folder name cannot contain : * ? " < > |',
  "Henüz hesap yok — 'Yönet' ile ekle.": "No accounts yet — add one with 'Manage'.",
  "Proxmox yedeğin ~1.5 saat sürüyorsa": "If your Proxmox backup takes ~1.5 hours then",
  "Saklanacak eski log dosyası sayısı.": "How many rotated log files to keep.",
  "sadece yerel (nginx/SSH tüneli ile)": "local only (via nginx/SSH tunnel)",
  "Yedeğin hiç ilerlememesini engeller.": "Keeps the backup from stalling completely.",
  " dolar. VM/CT'ler büyürse yer biter.": " full. If guests grow you will run out.",
  "'ini kullanır, büyümeye pay bırakır).": "of free space, leaving room to grow).",
  "Bildirim seçili ama alıcı adresi boş.": "Notifications are on but no recipient is set.",
  "Boş bırakırsan mevcut şifre değişmez.": "Leave empty to keep the current password.",
  "IP adresi yaz (0.0.0.0 veya 127.0.0.1)": "enter an IP address (0.0.0.0 or 127.0.0.1)",
  "ÇALIŞIR — yükleme başarısızsa da siler": "RUNS — deletes even if the upload failed",
  "Google hesabı seçilmedi — 3. adıma dön.": "No Google account selected — go back to step 3.",
  "Arayüzde gösterilecek log satırı sayısı.": "How many log lines the UI shows.",
  "Boş bırakırsan yukarıdaki alıcıya gider.": "Leave empty to use the recipient above.",
  "Tarayıcısı olan herhangi bir bilgisayarda": "On any computer that has a browser run",
  "Tıklayınca seçilir, kopyala-yapıştır yap.": "Click to select, then copy and paste.",
  "Önceki sürüme dönülecek. Devam edilsin mi?": "This rolls back to the previous version. Continue?",
  "Günde bir kez yeni sürüm var mı diye bakar.": "Checks once a day for a new version.",
  "Kota bu yüzdeyi aşarsa raporda uyarı çıkar.": "Warn in the report when quota exceeds this percentage.",
  "Hangi sonuçta mail gelsin. Bağımsız seçilir.": "Which outcomes trigger an email. Chosen independently.",
  "Trafik şifresiz — yalnızca VPN içinde kullan": "Traffic is unencrypted — use only inside a VPN",
  "dengeli. Hızın sürekli inip çıkıyorsa düşür.": "is balanced. Lower it if the speed keeps oscillating.",
  "Plan başına saklanacak çalışma geçmişi kaydı.": "Run history entries kept per plan.",
  "Boş = her gün. Haftalık arşiv için tek gün seç.": "Empty = every day. Pick one day for a weekly archive.",
  "Gereksiz ayar yapılmasını ve salınımı engeller.": "Prevents needless adjustments and oscillation.",
  "Hat çok meşgulken bile bu hızın altına inilmez.": "Never drops below this even when the link is busy.",
  "SMTP kullanıcı adı, genelde tam e-posta adresi.": "SMTP username, usually the full email address.",
  "Düzenlerken boş bırakırsan mevcut şifre korunur.": "Leave empty when editing to keep the current password.",
  "Profilin görünen adı. Plan formunda bu ad çıkar.": "Display name of the profile, shown in the plan form.",
  "Adres veya port değişirse servisi yeniden başlat:": "If the address or port changes, restart the service:",
  "' kaldırılsın mı? Drive'daki dosyalara dokunulmaz.": "' be removed? Files on Drive are not touched.",
  "Dosya adı deseni. Grup 1=set, 2=tip, 3=id, 4=tarih.": "Filename pattern. Group 1=set, 2=type, 3=id, 4=date.",
  "Klasör seçici yalnızca bu köklerin altını gösterir.": "The folder picker only shows paths under these roots.",
  "geçerli olur. Boş bırakırsan sabit sınır kullanılır.": "applies. Leave empty to use the fixed limit.",
  "Google hesaplarını yönet: kota, bağlantı testi, silme": "Manage Google accounts: quota, connection test, removal",
  "Sunucu, port ve güvenlik ayarını sağlayıcından öğren.": "Get server, port and security settings from your provider.",
  "Arayüz birkaç saniye yeniden başlar. Devam edilsin mi?": "The UI restarts for a few seconds. Continue?",
  "Şifreleme yöntemi. Sağlayıcı şablonu bunu da doldurur.": "Encryption method. The provider preset fills this in too.",
  "Hesaplar, mail profilleri, güvenlik ve gelişmiş ayarlar": "Accounts, mail profiles, security and advanced settings",
  "Firewall kurmaya gerek yok — kontrol uygulamanın içinde.": "No firewall needed — the check is inside the application.",
  "Haftada bir, son dönemin özetini ve uyarıları mail atar.": "Emails a weekly summary of the period plus warnings.",
  "Bu kadar gündür başarılı yedek yoksa raporda uyarı çıkar.": "Warn in the report after this many days without a successful backup.",
  "Hattın bu yüzdesi her zaman diğer uygulamalara bırakılır.": "This percentage of the link is always left to other applications.",
  "Kapsamlı silme yetmezse hesap geneli cleanup çalışsın mı.": "Run account-wide cleanup if scoped deletion is not enough.",
  "Mail profili yok — '✉ Yönet' ile ekle, yoksa mail gitmez.": "No mail profile — add one with '✉ Manage' or no mail is sent.",
  "Sertifika dosyası. Boş bırakırsan arayüz düz HTTP çalışır.": "Certificate file. Leave empty to run the UI over plain HTTP.",
  "güvenli. Çakışırsa zaten beklenir ama boşuna beklemeyelim.": "is safe. Overlap is handled anyway, but let us not wait for nothing.",
  "Her gün, 2 gün sakla, çöpte yarım gün. Kurulumu denemek için.": "Every day, keep 2 days, half a day in trash. For trying the setup.",
  "Yanlış silme olursa bu süre içinde Drive'dan geri alabilirsin.": "If something is deleted by mistake you can restore it from Drive within this window.",
  "Açıkken sınır yalnızca yüklemeye uygulanır, indirme etkilenmez.": "When on, the limit applies to uploads only; downloads are unaffected.",
  "Hatada retention açık: yeni yedek çıkmadan eskiler silinebilir.": "Retention on failure is on: old backups may be deleted before a new one lands.",
  "Hesabın içindeki hedef klasör. Yoksa ilk çalışmada oluşturulur.": "Target folder inside the account. Created on the first run if missing.",
  "Sabit yükleme hız sınırı. Çizelge doluysa çizelge önceliklidir.": "Fixed upload speed limit. The schedule takes precedence if set.",
  "Ham rclone argümanları. Buradaki her şey komut satırına eklenir.": "Raw rclone arguments. Everything here is appended to the command line.",
  "Rapor içinde: çalışma sayıları, yüklenen/silinen dosyalar, kota,": "The report contains: run counts, uploaded/deleted files, quota,",
  "Bildirimlerin gideceği adres. Virgülle birden fazla yazabilirsin.": "Where notifications go. Comma separate for multiple addresses.",
  "Hazır sağlayıcı seçersen sunucu, port ve güvenlik otomatik dolar.": "Picking a provider preset fills in server, port and security.",
  "Hiçbiri seçili değilse her gün çalışır. Seçersen sadece o günler.": "If none are selected it runs every day; otherwise only on those days.",
  "Mailde görünecek gönderen adresi. Boşsa kullanıcı adı kullanılır.": "Sender address shown in the mail. Falls back to the username.",
  "state.json'a yazılacak azami yedek/çöp satırı. Toplamlar tam kalır.": "Maximum backup/trash rows written to state.json. Totals stay exact.",
  "Aynı klasörü paylaşan iki plan birbirinin yedeğini eski sanıp siler.": "Two plans sharing a folder will treat each other's backups as old and delete them.",
  "Hesaplanan yeni sınır mevcuttan bu yüzdeden az farklıysa uygulanmaz.": "A new limit is not applied if it differs from the current one by less than this.",
  "Yeni sürüm bulununca kendiliğinden kurar. Kapalıyken sadece bildirir.": "Installs automatically when a new version is found; otherwise it only notifies.",
  "Bir VM 3 aydır yedeklenmiyorsa gün kuralı hepsini silerdi; bu ayar son": "If a VM has not been backed up for 3 months the day rule would delete everything; this keeps the last",
  "Bu araç zaten yükleme yapar; kapatırsan listeleme/indirme de yavaşlar.": "This tool only uploads; turning it off also slows listing and downloads.",
  "Aynı anda kaç dosya yüklensin. Bellek kullanımı: parça boyutu × bu sayı.": "How many files upload at once. Memory use: chunk size × this number.",
  "Her gün 02:00, Drive'da 30 gün, VM/CT başına en az 7 set, çöpte 3 gün.": "Every day at 02:00, 30 days on Drive, at least 7 sets per guest, 3 days in trash.",
  "Kapalıyken yükleme başarısızsa hiçbir yedek silinmez. Açmanız önerilmez.": "When off, nothing is deleted if the upload fails. Turning it on is not recommended.",
  "Regex. Varsayılan vzdump adlarını tanır — değiştirmen normalde gerekmez.": "Regex. Recognises default vzdump names — you normally do not need to change it.",
  "Bu desenlere uyan dosyalar hiç yüklenmez. vzdump geçici dosyaları burada.": "Files matching these patterns are never uploaded. vzdump temporary files go here.",
  "Test maili hangi adrese gitsin?\\n(boş bırakırsan gönderen adresine gider)": "Where should the test mail go?\\n(empty = the sender address)",
  "Arayüze yalnızca bu ağlardan erişilebilir. Boş bırakırsan kısıtlama olmaz.": "Only these networks may reach the UI. Leave empty for no restriction.",
  "Listede ve mail konularında görünecek ad. Plan kimliği bu addan türetilir.": "Name shown in the list and mail subjects. The plan id is derived from it.",
  "İnternet bağlantının toplam YÜKLEME kapasitesi. Hesaplamanın temeli budur.": "Your connection's total UPLOAD capacity. This is the basis of the calculation.",
  "iyi bir değer. Çok düşürürsen yazılmakta olan dosyayı yakalama riski artar.": "is a good value. Lowering it raises the risk of catching a file still being written.",
  "Her plan bu hesaplardan birine yazar. Başkasının hesabını da ekleyebilirsin.": "Each plan writes to one of these accounts. You can add someone else's account too.",
  "Her Pazar 05:00, Drive'da 180 gün, çöpte 7 gün, düşük hız. Uzun süreli arşiv.": "Every Sunday at 05:00, 180 days on Drive, 7 days in trash, low speed. Long-term archive.",
  "Saate göre değişen hız sınırı. Doluysa yukarıdaki sabit sınırın yerine geçer.": "Speed limit that varies by hour. Overrides the fixed limit above when set.",
  "%30 iyi bir başlangıç. Yükseltirsen daha nazik, düşürürsen daha hızlı olursun.": "30% is a good start. Raise it to be gentler, lower it to go faster.",
  "Güvenlik tabanı: VM/CT başına bu kadar set, gün sınırına bakılmadan korunur.": "Safety floor: this many sets per guest are kept regardless of the day limit.",
  "Her gün 03:00, Drive'da 14 gün, çöpte 1 gün. Çoğu kurulum için doğru başlangıç.": "Every day at 03:00, 14 days on Drive, 1 day in trash. The right start for most setups.",
  "Proxmox host üzerindeki klasörler. Parantez içi: tanınan vzdump dosyası sayısı.": "Folders on the Proxmox host. In brackets: number of recognised vzdump files.",
  "Gün cinsinden tüm değerler burada. Alan adlarının üstüne gelince açıklama çıkar.": "All day-based values are here. Hover a field label for an explanation.",
  "Kapalıysa zamanlayıcı bu planı atlar. Elle 'Yedekle' ile yine çalıştırabilirsin.": "When off the scheduler skips this plan. You can still run it manually with 'Back up'.",
  "Mailin hangi hesaptan gönderileceği. Mail düğmesinden yeni profil ekleyebilirsin.": "Which account sends the mail. Add a new profile from the Mail button.",
  "Çerezin yalnızca HTTPS üzerinden gönderilmesi. TLS açıkken zaten zorunlu tutulur.": "Send the cookie over HTTPS only. Already enforced when TLS is on.",
  "Hat boşken bile bu hızın üstüne çıkılmaz. Boşsa yukarıdaki sabit sınır tavan olur.": "Never exceeds this even when the link is idle. Empty means the fixed limit is the ceiling.",
  "Her plan istediği profilden mail atar. Farklı hesaplar, farklı sunucular olabilir.": "Each plan sends mail from the profile it chooses. Different accounts and servers are fine.",
  "Güvenlik tabanı 0: uzun süre yedeklenmeyen bir VM/CT'nin tüm yedekleri silinebilir.": "Safety floor is 0: all backups of a guest not backed up for a long time may be deleted.",
  "Google çöp kutusunda bekleme süresi. Bu süre dolunca kalıcı silinir ve kota boşalır.": "How long it waits in Google trash. After that it is permanently deleted and quota is freed.",
  "Proxmox'un vzdump çıktılarını yazdığı klasör. Depo başına ayrı bir dump klasörü olur.": "The folder where Proxmox writes vzdump output. Each storage has its own dump folder.",
  "Bu süre dolarsa tur atlanır ve sonraki kontrolde yeniden denenir. Hiçbir şey silinmez.": "If this expires the round is skipped and retried at the next check. Nothing is deleted.",
  "Yedeğin yükleneceği Google hesabı. Başkasının hesabını da ekleyip burada seçebilirsin.": "The Google account backups are uploaded to. You can add and pick someone else's account.",
  "Ölçümü yumuşatır. Düşük değer daha sakin, yüksek değer daha çevik ama salınıma yatkın.": "Smooths the measurement. Lower is calmer, higher is more responsive but prone to oscillation.",
  "Sadece bu kadar dakikadır değişmemiş dosyalar yüklenir. Yazılmakta olan yedek yarım gitmez.": "Only files untouched for this many minutes are uploaded, so a backup being written is not sent half finished.",
  "Karşılaştırma işçisi sayısı. Yüklemeyi değil, 'bu dosya zaten var mı' kontrolünü hızlandırır.": "Number of comparison workers. Speeds up the 'does this file already exist' check, not the upload.",
  "Planın başlayacağı saat (24 saat biçimi). Proxmox'un kendi yedek işi bittikten sonrasını seç.": "When the plan starts (24-hour clock). Pick a time after your Proxmox backup job finishes.",
  "Arayüzün dinleyeceği adres. 127.0.0.1 yaparsan sadece SSH tüneli/ters vekil üzerinden erişilir.": "Address the UI listens on. Use 127.0.0.1 to allow access only via SSH tunnel or reverse proxy.",
  "Senaryo seçmek formu doldurur; sonra istediğini değiştirebilirsin. Kaydetmeden hiçbir şey uygulanmaz.": "Choosing a preset fills the form; you can change anything afterwards. Nothing is applied until you save.",
  "Proxmox'un kendi yedeği çalışırken yüklemeye başlanmaz. Kilit dosyası, süreç ve yazılan dosyalar kontrol edilir.": "Uploading does not start while Proxmox's own backup runs. The lock file, process and files being written are all checked.",
  "Trafiğin ölçüleceği ağ arayüzü. Proxmox'ta köprü yerine fiziksel/bond arayüzü seçmek VM ve CT trafiğini de kapsar.": "Interface to measure traffic on. On Proxmox, picking the physical/bond interface instead of the bridge also covers VM and CT traffic.",
  "Hattaki diğer trafiği ölçüp yükleme hızını canlı ayarlar. Başka bir yedekleme yazılımı hattı kullandığında geri çekilir.": "Measures other traffic on the link and adjusts the upload speed live. Backs off when another backup tool uses the line.",
  "Kota ölçülüyor, birkaç saniye sonra tekrar bak.": "Measuring quota, check again in a few seconds.",
  "Kota okunamadı — doluluk hesaplanamıyor. Gereken alan yine de doğru.":
    "Quota unavailable — usage cannot be projected. The required space is still correct.",
  "Sığabilecek en uzun süre: <b>": "Longest period that fits: <b>",
  "'ini kullanır). Bu bir tavsiye değil, üst sınır.": "of free space). This is an upper bound, not a recommendation.",
  "Kısa süre daha az yer kaplar; uzun süre geç fark edilen bir soruna karşı daha geniş geri dönüş penceresi verir.":
    "A shorter period uses less space; a longer one gives a wider recovery window for problems noticed late.",
  "📐 Sığabilecek en uzun süreyi uygula": "📐 Apply longest period that fits",
  "🗜️ Az yer — 3 gün": "🗜️ Low space — 3 days",
  "Her gün 03:00, Drive'da 3 gün, çöpte 1 gün. En az yer kaplayan seçenek; son birkaç günü korur.":
    "Every day at 03:00, 3 days on Drive, 1 day in trash. The smallest option; keeps the last few days.",
  "Her gün 03:00, Drive'da 14 gün, çöpte 1 gün. Daha geniş geri dönüş penceresi, daha çok yer.":
    "Every day at 03:00, 14 days on Drive, 1 day in trash. Wider recovery window, more space.",
  "Gün sayısı arttıkça yer de artar.": "More days means more space.",
  "Onay": "Confirm", "Bilgi gerekli": "Input required", "Tamam": "OK",
  "Gün kuralı kapalı — yalnızca aşağıdaki set tabanı korur.":
    "Day rule disabled — only the set floor below protects backups.",
  "günden eski setler Google çöp kutusuna gönderilir.": "days and older are moved to Google trash.",
  "Günlük yedek alıyorsan Drive'da yaklaşık": "With daily backups Drive holds about",
  "set durur.": "sets.", "Ölçülene göre": "Measured, that is",
  "0 riskli: gün kuralı bir VM/CT'nin tüm yedeklerini silebilir.":
    "0 is risky: the day rule could delete every backup of a VM/CT.",
  "Bir VM/CT uzun süre yedeklenmese bile en yeni": "Even if a VM/CT is not backed up for a long time, the newest",
  "seti gün kuralından muaf tutulur.": "sets are exempt from the day rule.",
  "Taban gün sayısından büyük ya da eşit: pratikte saklamayı taban belirler.":
    "The floor is at or above the day count, so in practice the floor decides retention.",
  "0 = çöpe uğramadan hemen kalıcı silinir; yanlış silmede geri dönüş olmaz.":
    "0 = deleted permanently without using the trash; no way back if it was a mistake.",
  "Yanlış silme olursa": "If something is deleted by mistake you have",
  "içinde Drive'ın çöp kutusundan geri alabilirsin.": "to restore it from Drive's trash.",
  "Çöpte yaklaşık": "About", "bekler.": "waits in trash.",
  "Bu süreden eski setler Google çöp kutusuna gönderilir.": "Sets older than this go to Google trash.",
  "Gün kuralından muaf güvenlik tabanı.": "Safety floor, exempt from the day rule.",
  "Çöpte bekleme süresi.": "How long it waits in trash.",
  " gün · min ": " days · min ",
  "Yedeklemeyi başlat": "Start backup",
  "bu plan zaten çalışıyor": "this plan is already running",
  "Planı duraklat": "Pause plan",
  "Planı etkinleştir": "Enable plan",
  "zamanlama durur, dosyalara dokunulmaz": "scheduling stops; no file is touched",
  "plan duraklatıldı": "plan paused",
  "plan etkinleştirildi": "plan enabled",
  "Retention'ı şimdi çalıştır": "Run retention now",
  "süresi dolan setleri Drive çöpüne taşır": "moves expired sets to Drive trash",
  "Çöpü boşalt": "Empty trash",
  "çöpte süresi dolmuş dosyaları kalıcı siler": "permanently deletes expired files in trash",
  "Drive durumunu tazele": "Refresh Drive status",
  "Haftalık raporu şimdi gönder": "Send weekly report now",
  "bu planda rapor kapalı": "weekly report is off for this plan",
  "önce plana mail adresi gir": "add a mail address to the plan first",
  "Test maili gönder": "Send test mail",
  "Kopyasını oluştur": "Duplicate",
  " (kopya)": " (copy)",
  "kopya hazır — gözden geçirip kaydet": "copy ready — review and save",
  "Planı JSON olarak indir": "Download plan as JSON",
  "başka sunucuya taşımak için": "to move it to another server",
  "Kaynak klasörü kopyala": "Copy source folder",
  "Hedefi kopyala": "Copy target",
  "kaynak": "source",
  "hedef": "target",
  "Bu planın loglarını göster": "Show this plan's logs",
  "Planı sil": "Delete plan",
  "Bağlantıyı test et": "Test connection",
  "Kotayı yenile": "Refresh quota",
  "Hesap adını kopyala": "Copy account name",
  "hesap adı": "account name",
  "Kota bilgisini kopyala": "Copy quota info",
  "Hesabı kaldır": "Remove account",
  "Drive'daki dosyalara dokunulmaz": "files on Drive are not touched",
  "Sunucu adresini kopyala": "Copy server address",
  "sunucu": "server",
  "Profili sil": "Delete profile",
  "Log — ": "Log — ",
  "tümü": "all",
  "sistem": "system",
  "Bu satırı kopyala": "Copy this line",
  "satır": "line",
  "Görünen logu kopyala": "Copy visible log",
  "Log dosyası olarak indir": "Download as log file",
  "Yenile": "Refresh",
  "Sistem loglarına geç": "Switch to system logs",
  "Tüm logları göster": "Show all logs",
  "Dosya adını kopyala": "Copy file name",
  "dosya adı": "file name",
  "Satırı kopyala": "Copy row",
  "Tabloyu kopyala": "Copy table",
  "tablo": "table",
  "Yeni plan": "New plan",
  "Şimdi yenile": "Refresh now",
  "Google hesapları": "Google accounts",
  "SMTP profilleri": "SMTP profiles",
  "Ayarlar": "Settings",
  "panoya kopyalandı": "copied to clipboard",
  "kopyalanamadı — metni elle seçmen gerekiyor": "could not copy — select the text manually",
  "Yarım kalmış bir düzenleme var — ": "You have an unfinished edit — ",
  "Kaydedilmemişti. Geri yüklensin mi?": "It was not saved. Restore it?",
  "Yarım kalan düzenleme": "Unfinished edit",
  "Geri yükle": "Restore",
  "az önce": "just now",
  " dakika önce": " minutes ago",
  "yeni plan": "new plan",
  "taslak geri yüklendi — kaydetmedikçe uygulanmaz": "draft restored — nothing is applied until you save",
  "İptal": "Cancel",
  "Henüz plan yok. Sağ üstten + Yeni Plan ile başla.": "No plans yet. Start with + New Plan at the top right.",
  " gönderilmiş": " sent",
  " (varsayılan rota)": " (default route)",
  "Proxmox'ta köprü (vmbr0) yalnızca host trafiğini görebilir; ": "On Proxmox a bridge (vmbr0) only sees host traffic; ",
  "VM ve CT trafiğini de saymak için fiziksel veya bond arayüzünü seç.": "pick the physical or bond interface to also count VM and CT traffic.",
  "Yeni sürüm var: ": "New version available: ",
  " hazır": " ready",
  "%) · çöp: ": "%) · trash: ",
  " · boş: ": " · free: ",
  "● CANLI": "● LIVE",
  "○ yoklama": "○ polling",
  "Sunucu değişiklikleri anında gönderiyor": "The server pushes changes instantly",
  "Canlı akış yok — belirli aralıklarla yenileniyor": "No live stream — refreshing on a timer",
  "Zamanlama kapalı; dosyalara dokunulmaz.": "Scheduling is off; no file is touched.",
  "Bu plan henüz hiç çalışmadı. İlk çalışma: ": "This plan has never run yet. First run: ",
  "Son denemede iş yapılmadı — genelde vzdump hâlâ çalışıyordu. ": "The last attempt did no work — usually vzdump was still running. ",
  "Sebep kartın altındaki özet satırında yazar. Sonraki turda tekrar denenir.": "The reason is in the summary line under the card. It retries on the next tick.",
  "Canlı akış": "Live stream",
  "Canlı akış (SSE)": "Live stream (SSE)",
  "Diski tarama sıklığı (ms)": "Disk watch interval (ms)",
  "Eş zamanlı canlı bağlantı sınırı": "Concurrent live connection limit",
  "Oturum adres bağlama": "Session address binding",
  "Host yapılandırması": "Host configuration",
  "yedekleniyor · son ": "backed up · keeping last ",
  " arşiv saklanır": " archives",
  " · JSON görüntü dahil": " · JSON snapshot included",
  "yedeklenmiyor": "not backed up",
  "Yapılandırmayı da yedekle": "Back up host configuration",
  "pvesh JSON görüntüsü": "pvesh JSON snapshot",
  "Saklanacak arşiv (adet)": "Archives to keep",
  "Yapılandırma arşivini indir": "Download configuration archive",
  "Yapılandırmayı şimdi yedekle": "Back up configuration now",
  "Zamanlayıcı gecikmiş": "Scheduler is late",
  "Zamanlayıcı hiç çalışmadı": "Scheduler has never run",
  "Kontrol et: ": "Check: ",
  "(otomatik: ": "(automatic: ",
  "  · köprü": "  · bridge",
  "  ← önerilen": "  ← recommended",
  "Otomatik seçim: ": "Automatic choice: ",
  "elle secildi": "selected manually",
  "varsayilan rota": "default route",
  "Köprü (vmbr0) sayaçları VM'ler arası yerel trafiği de sayar — o trafik internete hiç çıkmaz, yükleme hızınla yarışmaz. Köprünün altındaki bond/fiziksel arayüz doğru ölçümü verir.": "A bridge (vmbr0) also counts VM-to-VM local traffic, which never reaches the internet and does not compete with your upload. The bond or physical interface under the bridge gives the correct measurement.",
  "Zamanlayici henuz hic calismadi.": "The scheduler has never run yet.",
  "Bağlandığın sunucu": "Server you are connecting to",
  "Oturum sahibi": "Signed in as",
  "Oturumu kapat": "Sign out",
  "⎋ Çıkış": "⎋ Sign out",
  "Kaydedilmemiş değişiklikler var. Yine de çıkılsın mı?": "You have unsaved changes. Sign out anyway?",
  "Çıkış": "Sign out",
  "Çık": "Sign out",
  "Yedek hedef yok — sadece birincil kullanılır.": "No fallback targets — only the primary is used.",
  "klasör": "folder",
  "Yukarı taşı": "Move up",
  "Bu hedefi kaldır": "Remove this target",
  "⚠ ": "⚠ ",
  " hedef birincil ile aynı hesapta — hesap kilitlenirse işe yaramaz": " target(s) are on the same account as the primary — useless if that account is locked",
  " yedek hedef tanımlı": " fallback target(s) configured",
  "Yedek hedefler": "Fallback targets",
  "yok — sadece birincil hedef": "none — primary target only",
  "Birincil çalışmazsa sırayla denenir: ": "Tried in order if the primary fails: ",
  " yedek": " fallback",
  "Son yazılan": "Last written to",
  "  (denenmedi)": "  (untested)",
  "Gerçek hesapla uçtan uca doğrulandı.": "Verified end to end with a real account.",
  "OAuth akışı çalışıyor ama yükleme/saklama davranışı gerçek hesapla denenmedi. Önce küçük bir planla dene.": "The OAuth flow works, but upload/retention behaviour has not been tested with a real account. Try a small plan first.",
  "Kapsam drive.file: yalnizca bu aracin olusturdugu dosyalari gorur, Drive'inin gerisine erisemez.": "Scope drive.file: it only sees files this tool created and cannot reach the rest of your Drive.",
  "Bazi kurumsal hesaplarda drive_id/drive_type de gerekir; gerekirse hesabi rclone config ile elle kur.": "Some business accounts also need drive_id/drive_type; if so, configure the account manually with rclone config.",
  "Oturumu kapatmak istediğine emin misin?\n\"Beni hatırla\" işaretlemiş olsan bile hatırlanan oturum silinir.": "Are you sure you want to sign out?\nEven if you ticked \"Remember me\", the remembered session is deleted.",
  "Bakım ve taşıma": "Maintenance and migration",
  "Ayarları taşı": "Migrate settings",
  "⬇ Ayarları indir": "⬇ Download settings",
  "⬇ Şifrelerle indir": "⬇ Download with passwords",
  "⬆ Ayar dosyası yükle": "⬆ Upload settings file",
  "Proxmox linki": "Proxmox link",
  "🔗 Proxmox'a link ekle": "🔗 Add link to Proxmox",
  "Kaldır": "Remove",
  "Açık oturumlar": "Open sessions",
  "Cihaz": "Device",
  "Adres": "Address",
  "Açılış": "Opened",
  "bu tarayıcı": "this browser",
  "Hatırlanan açık oturum yok.": "No remembered sessions.",
  "Hatırlama: ": "Remember me: ",
  "açık": "on",
  "adres bağlama: ": "address binding: ",
  "Diğer tüm oturumları kapat": "Close all other sessions",
  "Bu tarayıcı dışındaki tüm hatırlanan oturumlar kapatılsın mı?": "Close every remembered session except this browser?",
  "Oturumlar": "Sessions",
  "İndirilecek dosya SMTP şifrelerini düz metin içerecek.\nYalnızca güvendiğin bir yere kaydet.": "The downloaded file will contain SMTP passwords in plain text.\nSave it somewhere you trust.",
  "Şifrelerle indir": "Download with passwords",
  "İndir": "Download",
  "dosya geçerli JSON değil": "file is not valid JSON",
  "Dosyada ": "The file has ",
  " plan, ": " plan(s), ",
  " mail profili var": " mail profile(s)",
  " (sürüm ": " (version ",
  "Mevcut planların korunsun mu, yoksa yerlerine bunlar mı geçsin?": "Keep your existing plans, or replace them with these?",
  "Ayar yükle": "Load settings",
  "Ekle (mevcutlar kalsın)": "Add (keep existing)",
  "Durum okunamadı: ": "Could not read status: ",
  "Link ekli: ": "Link is in place: ",
  "Link yok. Eklenecek adres: ": "No link. Address to add: ",
  "durum okunamadı": "could not read status",
  "okunamadı": "could not read",
  "Çalışan betik değişmiş": "The running script has changed",
  "Güncelleme yaptıysan normaldir; referansı yenile: ": "Normal if you just updated; refresh the baseline: ",
  "Betik okunamadi.": "Could not read the script.",
  "Butunluk referansi henuz alinmadi.": "Integrity baseline not taken yet.",
  "Calisan betik degismis. Beklenen {b}…, bulunan {s}…. Guncelleme yaptiysan normaldir; yapmadiysan INCELE.": "The running script changed. Expected {b}…, found {s}…. Normal if you updated; if not, INVESTIGATE.",
  "Telegram bildirimi": "Telegram notifications",
  "Bot jetonu": "Bot token",
  "Sohbet (chat id)": "Chat (chat id)",
  "✈ Test mesajı gönder": "✈ Send test message",
  "jeton kayıtlı": "token saved",
  "jeton girilmemiş": "no token",
  "önce bot jetonunu gir ve kaydet": "enter the bot token and save first",
  "önce Kaydet'e bas, sonra test et": "press Save first, then test",
  "Sunucu etiketi": "Server label",
  "(boş = sunucu adı)": "(empty = hostname)",
};
